### ISSUE TITLE
Fails when trying to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by alexmyczko** [schik/burn#3]
Making all for app Burn...
 Creating obj/Burn.obj/Inspectors/...
 Creating Burn.app/....
 Compiling file main.m ...
 Compiling file AppController.m ...
 Compiling file ConsolePanel.m ...
 Compiling file Constants.m ...
 Compiling file ProjectWindowController.m ...
 Compiling file ProjectWindowController+DnD.m ...
 Compiling file ProjectWindowController+OlvDelegate.m ...
 Compiling file PreferencesWindowController.m ...
 Compiling file ParametersWindowController.m ...
 Compiling file Project.m ...
 Compiling file Project+Audio.m ...
 Compiling file Project+Data.m ...
 Compiling file Track.m ...
 Compiling file Functions.m ...
Functions.m:26:10: fatal error: AudioCD/AudioCDProtocol.h: No such file or directory
 #include <AudioCD/AudioCDProtocol.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/usr/share/GNUstep/Makefiles/rules.make:479: recipe for target 'obj/Burn.obj/Functions.m.o' failed

ah that comes with cdplayer...
